### ISSUE TITLE
SR: news post defaulting to left align

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1024]
The text is pushed to the left side without left align being selected:

https://www.cityofsanrafael.org/city-administrative-offices-closed-independence-day/
![screenshot 2017-06-26 15 44 11](https://user-images.githubusercontent.com/6032426/27557112-5d3a0134-5a86-11e7-8777-14ee12032cca.png)

**Comment by jlyon** [comment]
This page looks like it has been deleted @kevindherman. 

I don't know why the body text wouldn't be the full width of the picture, but I think the reason it was poking out on the left is because the flag picture is getting resized and then centered.

Example: https://www.cityofsanrafael.org/2017-point-time-count/

**Comment by kevindherman** [comment]
@jlyon I'll keep an eye out. This can be closed.
