### ISSUE TITLE
Increase size limit to show document preview from 10mb to 20mb

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1056]
This document isn't previewing but under 20MB:

https://www.cityofsanrafael.org/documents/critical-facilities-strategy-committee-report-april-2005/

I've tried reloading the file and that doesn't work. 

This appears to be isolated to this specific doc.

**Comment by jlyon** [comment]
@kevindherman url?

**Comment by jlyon** [comment]
https://www.cityofsanrafael.org/documents/critical-facilities-strategy-committee-report-april-2005/

**Comment by jlyon** [comment]
@kevindherman  It looks like we lowered the limit to 10mb because a 23mb file wasn't displaying: https://github.com/proudcity/wp-proudcity/issues/139. 

I tested this file and it works if I un-hide it, so we could try to play the game of increasing the limit to try to find the sweet spot, or we could just communicate that the limit is 10mb.

**Comment by kevindherman** [comment]
@jlyon ah, I thought it was 20mb across the board.

**Comment by jlyon** [comment]
is it 20 for search?  If so, we should change it for the preview and just deals with the consequences of the one-off 18mb upload.

**Comment by kevindherman** [comment]
@jlyon we did 20MB for search because I thought that was what the preview was at. If we can do 20MB and monitor the effects that would be my vote.

**Comment by jlyon** [comment]
Make this update, will get pushed in next release.
