### ISSUE TITLE
Lucas: drag and drop doc order

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1119]
@jlyon the drag and drop feature for ordering documents is disabled only on Lucas' site.

https://www.lucastexas.us/wp-admin/edit.php?post_type=document&orderby=title&order=asc
![screenshot 2017-09-19 15 47 45](https://user-images.githubusercontent.com/6032426/30612230-e88292fc-9d51-11e7-99a0-9c0408a4db87.png)

If you try and grab an item the cursor doesn't change to the drag and drop feature but it does work correctly on other sites I tested.

**Comment by jlyon** [comment]
Yes, this is because they are no longer sorting their documents by drag and drop, they are now sorting them automatically by date posted: 
![screenshot 54](https://user-images.githubusercontent.com/550909/30617048-3b7ee392-9d49-11e7-8c96-32501be122fb.png).

This was implemented after this release: https://github.com/proudcity/wp-proudcity/issues/1097.  Is this not what should be happening for them @kevindherman ?

**Comment by kevindherman** [comment]
@jlyon is that feature per widget or per site? So if you enable sort by post date can you no longer use drag and drop for other document list widgets?

**Comment by jlyon** [comment]
@kevindherman No, it is per list widget.  I just disabled the drag and drop on Lucas because it seemed like it was a consistent source of struggle.

**Comment by kevindherman** [comment]
@jlyon yeah, could you re-enable it? I'll then explain the per widget thing to them better which will hopefully ease the struggle.

**Comment by jlyon** [comment]
@kevindherman Just re-enabled it.  I'll avoid disabling the drag n drop in the future.

**Comment by kevindherman** [comment]
@jlyon this can be closed.

**Comment by aschmoe** [comment]
@kevindherman, as you know, the hard part is that updating the order will not be reflected necessarily .  They must then save the documents after ordering them for the process to actually take hold.  Not ideal but a work-around
