### ISSUE TITLE
Allow job posting display customizations

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1143]
From Kettering:

I am getting some pretty strong push back from our HR department on a few items they want to see changed with job postings.

1.  They want the apply now button removed.  We don't have online app process, so the button really does nothing other than reiterate what is already in text.  I went in to job posts and tried to find way to remove button but couldn't figure it out.

2. The expiration date for the job posts automatically populates to be 30 days after original post and then removes post from listing.  Most of our recruitments are open much longer than that.  HR would like that field removed entirely and move to manually archiving the job posts.

@aschmoe @jlyon it would be great to get this into the next release.

**Comment by jlyon** [comment]
Gravityforms + WP Job Manager: 1144

**Comment by jlyon** [comment]
@kevindherman I removed the expiration date from new job listings.  I also made it so previously expired listings still appear in the list, and you can see the details `Your site will display the titles of expired listings, but not the content of the listings. Otherwise, expired listings display their full content minus the application area.`

Removing the Apply button will take a new settings and/or some theme tweaking.

**Comment by kevindherman** [comment]
@jlyon thank you.

The apply button can happen with the release.
