### ISSUE TITLE
Vote app doesn't allow you to submit address

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1258]
https://www.cityofdeleon.org/vote/#/city/vote/address
![screenshot 2018-01-29 10 31 18](https://user-images.githubusercontent.com/6032426/35518442-97c62d60-04df-11e8-899f-cfdd8357a944.png)

If you enter an address into the vote app you're unable to submit the entry. Return or select the search button doesn't do anything.

Here's a test address:

125 S Texas ST, De Leon TX 76444

**Comment by jlyon** [comment]
@kevindherman seems like there are 2 issues:

1. We needed to select the current election.  I guess this api now has different elections in different places.  We may need to build out some interface, but for now I set it to the TX election:
<img width="909" alt="screen shot 2018-01-29 at 9 24 10 pm" src="https://user-images.githubusercontent.com/550909/35556951-8ca37dec-0558-11e8-8afd-aeaeeba1a00b.png">

2. After setting the election, it's now working for me on https://www.cityofdeleon.org/vote/ if I use the "Use my location". It looks like there's some issue with the address Geocoding that I'll have to look into more later.  Hitting the search button doesn't do anything, and clicking enter throws this js err:
![screen shot 2018-01-29 at 11 41 13 am](https://user-images.githubusercontent.com/550909/35557190-3a22b05a-0559-11e8-850a-40c9c58a08f3.png)

**Comment by kevindherman** [comment]
@jlyon I'm still having issues from an incognito window.

I noticed that the page redirects /vote to https://www.cityofdeleon.org/vote#/city/vote/address

**Comment by jlyon** [comment]
Yeah there's something breaking the address selection that I still need to
look into.  Only the use my location button currently works.

On Jan 30, 2018 7:17 AM, "kevindherman" <notifications@github.com> wrote:

@jlyon <https://github.com/jlyon> I'm still having issues from an incognito
window.

I noticed that the page redirects /vote to https://www.cityofdeleon.org/
vote#/city/vote/address

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/proudcity/wp-proudcity/issues/1258#issuecomment-361624552>,
or mute the thread

**Comment by jlyon** [comment]
@kevindherman it looks like we're not getting any info back for that test address (125 S Texas ST, De Leon TX 76444).  The Google API we're using returns `"No information for this address"
` for that address, but works for my address (which is why the locate button works).

 The actual address selection functionality does seem to be working though, so I'm closing.
