### ISSUE TITLE
Remove link on TEST in proudbar

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1260]
Can we remove the link on the 'TEST' text in the proudbar?

<img width="1207" alt="screen shot 2018-01-29 at 4 18 03 pm" src="https://user-images.githubusercontent.com/1569463/35541554-4277bd52-0510-11e8-9569-1f16a3b6f4a3.png">

**Comment by lukefretwell** [comment]
Now that I think about it, do we really need it?

**Comment by jlyon** [comment]
Removed the link @lukefretwell. I changed TEST to BETA.

I did not change the bg color because it looked pretty bad when you scrolled to the bottom of the page:
![screenshot 51](https://user-images.githubusercontent.com/550909/35550649-4c0221ca-0540-11e8-9a8c-50fad9566690.png)


This will all be pushed in our next release.

**Comment by kevindherman** [comment]
@lukefretwell @jlyon the distinction between TEST and BETA was a sales thing. A test site meant it was a lead whereas BETA is a customer.
