### ISSUE TITLE
Danvers: recurring event, unable to edit date range

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1429]
When trying to extend a recurring event beyond the current date, it reverts back after hitting update.

Danvers Veteran Social:
https://www.danversma.gov/wp-admin/post.php?post=14119&action=edit

1- edit recurring event
2- edit end date to June 27, 2019
3- update
4- recurrence span date goes back to Dec 27, 2018 (previous date)

@jlyon @aschmoe

**Comment by jlyon** [comment]
@kevindherman I'm definitely able to replicate this on https://www.danversma.gov/wp-admin/post.php?post=15711&action=edit.

@aschmoe do you remember adding a limit to the date range for recurring events to reduce performance issues with `get_title()`? Could that be what's happening here?  It's weird because I'm not even able to change the end date to an earlier date (say Dec 21 2018).

**Comment by aschmoe** [comment]
@kevindherman this should be fixed, we had an old template override in the theme.

**Comment by aschmoe** [comment]
addressed in #1474
