### ISSUE TITLE
Image floats + paragraph breaks causing spacing issues on mobile

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#148]
Not sure how exactly to handle this, but https://west-carrollton-oh.proudcity.com/fire-captains/ on mobile is messed up since paragraph line breaks hiding behind image floats on desktop...

@jlyon any thoughts?

![fire captains - west carrollton](https://cloud.githubusercontent.com/assets/1634686/12991758/966347dc-d0c5-11e5-82e7-6d04a221b563.png)

![fire captains - west carrollton 1](https://cloud.githubusercontent.com/assets/1634686/12991785/b437b644-d0c5-11e5-9023-60137021b3df.png)

**Comment by aschmoe** [comment]
We could maybe make those spacing paragraphs clear: both

**Comment by jlyon** [comment]
i think we should encourage them to use panels instead of floating images, or add an hr between after floated images in cases like these that we could `clear:both` on (and make act like a `.clearfix`).

I think adding clears to `<p>`s would cause a lot of problems, and it's prob not great moving forward, but would work here prob.

@kevindherman tagging you so you're aware for future training.

**Comment by kevindherman** [comment]
Roger that.

@jlyon maybe a good thing to review on the call tomorrow with the pilot.
