### ISSUE TITLE
Petaluma: department template

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1579]
Make this page into Department Layout Option: https://petaluma-ca.proudcity.com/template-department-1/

**Comment by jlyon** [comment]
@kevindherman I started looking into this and I don't think it will be hard once we have the finalized department template signed off on.  I think it's best to use the Example Department I setup (https://petaluma-ca.proudcity.com/departments/example-deparment/), because it has all of the menu stuff working.

**Comment by kevindherman** [comment]
You can implement now.

**Comment by jlyon** [comment]
@kevindherman This has been added. To select:
1. Create new dept
2. Click Layouts in the panels editor bar
3. Select the Petaluma Department template
4. Click insert
5. Click Replace
6. Click "Are you sure?"
7. Edit widgets and Save Department
![Screenshot (24)](https://user-images.githubusercontent.com/550909/59580468-18f15f80-9086-11e9-9493-176ee3deaf89.png)
