### ISSUE TITLE
Petaluma: custom image widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1582]
Create custom image widget that allows formatting like the images that look like the card view on this page: https://petaluma-ca.proudcity.com/template-department-1/

This will also allow the images to be full width on mobile view which it currently isn't:
<img width="487" alt="Screen Shot 2019-06-13 at 10 49 28 AM" src="https://user-images.githubusercontent.com/6032426/59464174-bda93e00-8df5-11e9-883b-af6cde0e2260.png">

**Comment by aschmoe** [comment]
@jlyon related to #1578 

- Need images for widget to be larger so as to fit in mobile view
- Title text box with brown text background same as cards
- Centered
- 2 sizes: tall, short

**Comment by jlyon** [comment]
It turns out we didn't really need the widget. Here's an overview of the settings @kevindherman 
<img width="1104" alt="Screen Shot 2019-06-14 at 12 07 37 AM" src="https://user-images.githubusercontent.com/550909/59490032-8314c500-8e38-11e9-989f-485dfa0a6fca.png">


We might want to make the text part of the link, which will just take a little work @kevindherman.

**Comment by jlyon** [comment]
Current status on the department template: I created an actual example department at https://petaluma-ca.proudcity.com/departments/example-deparment/. There are two outstanding issues:
1. Outstanding issues with the width of the columns in the 1-1-2-1 layout
2. The mobile menu stuff still needs to be fixed.

Both of these issues can be fixed with CSS.  The actual department template used on https://petaluma-ca.proudcity.com/departments/example-deparment/ is fine to start using to set up departments (you can export, and then import for now, but I'll set up the "Saved template" over the weekend @kevindherman ).

I'll talk to @aschmoe about these issues tomorrow and should be able to get everything all set over the weekend @kevindherman.

**Comment by kevindherman** [comment]
@jlyon @aschmoe just to make sure I understand the 1-1-2-1 issue will address the images being equal height like it was previously, right?

**Comment by jlyon** [comment]
@kevindherman this has been fixed on https://github.com/proudcity/wp-proudcity/issues/1576.  Additional screenshot of setup steps is over there
