### ISSUE TITLE
Fix jumbtron inverse styles

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1622]
![Screenshot of Home - Bedford](https://user-images.githubusercontent.com/1634686/66183118-70fba400-e62c-11e9-899b-f69ec5c7c226.jpg)

**Comment by kevindherman** [comment]
@lukefretwell This fix changed the department headers on city-template:

https://city-template.proudcity.com/departments/police/

Is this because of styles you did or do we need to adjust our approach here?

cc @jlyon @aschmoe

**Comment by kevindherman** [comment]
@lukefretwell @aschmoe @jlyon I switched the hero unit from light background with black text to dark background with white text:

![Screenshot 2019-11-08 10 02 35](https://user-images.githubusercontent.com/6032426/68486448-10551d80-020f-11ea-807a-d4983f944ec2.png)
![Screenshot 2019-11-08 10 03 00](https://user-images.githubusercontent.com/6032426/68486449-10551d80-020f-11ea-9e5c-bd0aef5f42a8.png)

I then noticed that the banner color was different from the main nav, which might not be a problem, but that's the case because it pulls the primary color:
![Screenshot 2019-11-08 10 04 33](https://user-images.githubusercontent.com/6032426/68486523-3bd80800-020f-11ea-88e1-ca58a864098c.png)

@lukefretwell is this what we want for city-template?

**Comment by lukefretwell** [comment]
@kevindherman yeah, we'll need to set the backgrounds for all of those to white text on dark background for any hero headers with the blue background. I did this for all the help pages.
