### ISSUE TITLE
Add GovDelivery <!--PAGEWATCH--> tags

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1702]
Insert this at the beginning of the Header content: 

Insert this at the end of the Header content:

**Comment by kevindherman** [comment]
@jlyon I got the below email that they're still getting a lot of extra alerts. Is this still an open issue?

Email:
I am still receiving hourly messages from GovDelivery for the MarinRecovers.com URL (https://marinrecovers.com/agencies/guidelines-for-businesses/). What that tells me is that the code snippet may not have been placed in the appropriate content area. It should be placed around header content and separately, around footer content, so that only page content gets “watched”.

**Comment by jlyon** [comment]
Fixed this for real @kevindherman. There was an issue with our minification settings in production.

For future reference, if other sites need this in the future, we need to add `PAGEWATCH` to "Ignored comment stems:" on /wp-admin/admin.php?page=w3tc_minify.
