### ISSUE TITLE
Carousel accessibility

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1725]
Looks like we need to add a background to the carousel text, just as we do for hero units.

**Comment by aschmoe** [comment]
@lukefretwell could you be more specific please?  Here's what I see when I add a carousel:

(as top header)
![Screen Shot 2021-12-02 at 8 54 09 PM](https://user-images.githubusercontent.com/1634686/144547465-f2f06fc4-1e80-4ef7-8104-7cd1e048f039.png)
(as mid-page slider)
![Screen Shot 2021-12-02 at 8 59 06 PM](https://user-images.githubusercontent.com/1634686/144547945-40b1dfdd-2ebf-46c4-b0c3-9ff33bac63f9.png)

Do we need to increase the contrast?  Looks to me to be the same as the normal "JumboTron"... if you have a link or otherwise would be great.  Thanks!

**Comment by lukefretwell** [comment]
@aschmoe I'm going to close this as I think it's 'fine' but mostly just don't want to focus on the carousel as a feature and think we just need to discourage use of.

cc @kevindherman
