### ISSUE TITLE
Allow thumbnails and cross site category filters for teasers in enhanced search

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1735]
I noticed some issues with the news posts. Not sure I'm missing something or there's a bug, especially on the second item below.

- [x] Thumbnails not showing
- [x] Posts not showing
- [x] Internal issue

## Thumbnails not showing

The thumbnails for the secondary site selected (in this case help.proudcity.com) aren't showing.

See here under 'Help' h2: https://proudcity.com/security/

## Posts not showing

I've selected the security category, but only one of the posts are showing up on the above page.

However, there are three posts in security: https://help.proudcity.com/security

## Internal issue

Can we get the main site (proudcity.com) added to help (help.proudcity.com)? Looks like it's not set up to pull from there, so on the help site it's just repeating help posts.

See here: https://help.proudcity.com/accessibility/

**Comment by aschmoe** [comment]
@lukefretwell  

> Thumbnails not showing

Working on it

> Posts not showing

Could you be more specific?

> Internal issue

This should be fixed

**Comment by lukefretwell** [comment]
@aschmoe re: 'Posts not showing'

- On help.proudcity.com there's security news that's pulling from the CMS (see 'Latest news' section): https://help.proudcity.com/security/
- And I added the news widget on proudcity.com to pull from help.proudcity.com, but those posts aren't showing (see 'Help' section): https://proudcity.com/security/

Security is checked as a category for both sites.

proudcity.com:

<img width="449" alt="Screen Shot 2020-08-25 at 2 00 17 PM" src="https://user-images.githubusercontent.com/1569463/91228171-a691fb80-e6dc-11ea-8b46-ffd0839016b4.png">

help.proudcity.com:

<img width="478" alt="Screen Shot 2020-08-25 at 2 10 00 PM" src="https://user-images.githubusercontent.com/1569463/91228306-dccf7b00-e6dc-11ea-9c95-63f6ea825eac.png">

**Comment by aschmoe** [comment]
@lukefretwell think this is tidied up.  Came up with a slightly messy solution for the external category filters since the core of the issue in the `Posts not showing` component is the category IDs on proucity.com didn't match the desired category IDs on help.proudcity.com, so I introduced a new input for that purpose.  If more sites begin trying to cross link things beyond search, we will have to come up with some better UI / flow for this

![Screen Shot 2020-08-27 at 10 52 42 PM](https://user-images.githubusercontent.com/1634686/91526382-596a8100-e8b8-11ea-8a6a-976cffbce9fe.png)

**Comment by lukefretwell** [comment]
@aschmoe 💥 

Thank you!
