### ISSUE TITLE
williams county: side by side widgets not aligned

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1763]
https://williams-county-nd.proudcity.com/about/

The widget titles for text (about) and facebook (facebook) should be on the same row but facebook is lower:
<img width="1097" alt="Screen Shot 2020-10-30 at 3 06 24 PM" src="https://user-images.githubusercontent.com/6032426/97746923-89552100-1ac1-11eb-83a5-efaa08b4f753.png">
<img width="862" alt="Screen Shot 2020-10-30 at 3 06 34 PM" src="https://user-images.githubusercontent.com/6032426/97746928-89edb780-1ac1-11eb-948c-675b8adf71e4.png">

@aschmoe ^

**Comment by lukefretwell** [comment]
@aschmoe @kevindherman looks like it's because the `h1, .h1, h2, .h2, h3, .h3` class has margin-top that should probably be the same as the `widget-title` class.

<img width="1424" alt="Screen Shot 2020-10-30 at 1 11 56 PM" src="https://user-images.githubusercontent.com/1569463/97752698-c3b6c200-1ab1-11eb-948c-d3d6c9885c75.png">
