### ISSUE TITLE
Add the ability to display text labels next to navbar action icons (particularly for Translation)

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1824]
Per conversation with @kevindherman, let's discuss the best plugin/solution for translation services (both public facing and admin).

**Comment by kevindherman** [comment]
@lukefretwell what was the multi-lingual site plugin you found around discussions with Monterey or Santa Barbara?

**Comment by kevindherman** [comment]
multi-lingual WP tool https://wpml.org/

**Comment by kevindherman** [comment]
Some suggestions from Solano Redistricting that may help with what we're working with right now with google translate:
https://redistricting.solanocounty.com/

1 - Have a more obvious icon or the word translate:
Having the word translate would be really helpful but there are obvious space concerns with that. Perhaps this as an icon replacement is a happy medium: https://1000logos.net/wp-content/uploads/2020/05/Emblem-Google-Translate.jpg
2- Have the language dropdown show language names in their respective languages
![image](https://user-images.githubusercontent.com/6032426/123269620-23dcf700-d4cd-11eb-9b5d-91e546de246e.png)
3- Is there a way to hack the primary menu to have "translate" that is just static to the far right so it sits next to the icon?

Just trying to throw some feedback in here since we have a lot of customers who are trying to do be better with what's available which is a challenge for everyone. 

@jlyon @aschmoe @lukefretwell lets chat to see if any of these are good ideas and possible.

**Comment by kevindherman** [comment]
future option to have text next to all top bar icons that can be enabled and disabled.

**Comment by jlyon** [comment]
@kevindherman got most of the way there on this one, but ran into some annoying formatting gotchas

**Comment by jlyon** [comment]
@kevindherman added "Navbar button style" option to the bottom of the Service Center > Settings page:
![Screen Shot 2021-08-05 at 4 59 49 PM](https://user-images.githubusercontent.com/550909/128459109-97a58a67-1c79-4c94-884a-0689020d74f5.png)

This is what it looks like:
![Uploading Screen Shot 2021-08-05 at 10.09.32 PM.png…]()

**Comment by kevindherman** [comment]
@jlyon @aschmoe this looks great.

I think there is something custom on Petaluma that is hiding the text for just translate when this is enabled. Can you take a look because I think they'll definitely want to use this if working.
