### ISSUE TITLE
Inverse Iconset and icon link option for dark bg with white text

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1827]
Add the ability to inverse iconsets and icon links to have dark background with white text (similar to simple heading color option).

**Comment by jlyon** [comment]
Started on this one and got most of the way there @kevindherman but didn't quite finish it. It'll go out in the next release.

**Comment by jlyon** [comment]
@kevindherman I pushed what we have to beta.proudcity.com.  The text needs to be white instead of black, but what do you think? Should the icon also be white?  Do you like the fade around the edges?
<img width="602" alt="Screen Shot 2021-03-25 at 11 27 48 PM" src="https://user-images.githubusercontent.com/550909/112592123-b1238900-8dc2-11eb-89d2-3fbb1a80d43f.png">
<img width="638" alt="Screen Shot 2021-03-25 at 11 32 33 PM" src="https://user-images.githubusercontent.com/550909/112592131-b41e7980-8dc2-11eb-9cd7-f1b0c1ffd9b0.png">

**Comment by kevindherman** [comment]
@jlyon @aschmoe yeah I think everything should be white. I'd match the dark bg and white text that's used for the simple heading option in the hero unit widget.

**Comment by kevindherman** [comment]
@jlyon per our discussion today, this should use the primary color instead of the secondary.

**Comment by jlyon** [comment]
Updated this to have a background with the primary color instead of the secondary color.
