### ISSUE TITLE
Danvers: publishing news or pages is stuck in draft

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1838]
Only able to move from draft to published from the quick edit option. There is not an option available to publish from the specific page or post, even from info@ account.

**Comment by kevindherman** [comment]
Another way this is coming up is that newly created pages are published but show as pending in the menu editor:  https://www.danversma.gov/wp-admin/nav-menus.php

If you save the menu it publishes the page.

I'm sure it's all related but no clue if that helps uncover what's going on. @jlyon

**Comment by kevindherman** [comment]
@jlyon since we have had several unique issues with Danvers that are challenging since it's more unique than our usual sites would it be a better use of time to migrate them to a more stable instance? I have no clue what the level of effort would be to do that but I'm curious on if that's a better use of time so things like this and stability would be more consistent with the rest of the platform. 

Let's brainstorm on this on the dev review when you're back.

**Comment by jlyon** [comment]
@kevindherman I spent a while testing around this. The core issue is that they have a ton of menus (85). The code for the menu selector widget in the sidebar is kinda janky and really doesn't like a ton of menus.  I clicked through https://www.danversma.gov/wp-admin/customize.php?autofocus%5Bpanel%5D=nav_menus&return=%2Fwp-admin%2Fnav-menus.php and it looked like at least half of their menus were empty. This caused this issue, but is also likely causing the create/edit pages to load slowly and could be slowing down the whole site in general.

It turned out this publishing issue could be fixed by dragging the menu block below the publish block. This is fixed for them now, but this is just a temporary hack.

Going forward, we should look to delete all of the unused (empty) menus.

**Comment by kevindherman** [comment]
@jlyon I'll reach out about deleting all those single page departments that aren't using a menu.

I have had multiple tickets on people accidentally dragging and dropping editor items which sounds like triggered this issue. Can we lock them into place or at least take away that permission for our customers?
