### ISSUE TITLE
Williams County: image gallery widget display not saving.

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1851]
https://www.williamsnd.com/blacktail-dam/

If you edit the the gallery widget > edit gallery > change gallery settings to slider or lightbox > update and save the page, those settings don't actually save. When you then view the page it doesn't show the changes and when you go back to the gallery settings it goes back to the defaults. 

<img width="1164" alt="Screen Shot 2021-05-13 at 3 12 38 PM" src="https://user-images.githubusercontent.com/6032426/118182235-c1410780-b406-11eb-8cc1-31a79041e150.png">

**Comment by jlyon** [comment]
@kevindherman I wasn't able to get the advanced settings (like lightbox) in a test gallery I created on beta.proudcity.com: https://beta.proudcity.com/wp-admin/post-new.php?post_type=page&wp-post-new-reload=true.  Do you know how they set that up?

**Comment by kevindherman** [comment]
@jlyon beta must be dated because you're right those options aren't there. However, when I messed with the presentation site which is more or less my sandbox and is newer I do get those advanced options, see the gallery widget on this page: https://presentation-ca.proudcity.com/division/

I was able to drop in the gallery widget and once you add images it's on the right.

**Comment by jlyon** [comment]
Weird, I'll take another look.

**Comment by kevindherman** [comment]
Here's the Lucas TX page that came up this week: https://www.lucastexas.us/departments/city-council/

**Comment by kevindherman** [comment]
@jlyon here's another site with the gallery widget being funny:

https://www.cityofmontclair.org/local-transportation/

The gallery displays but the popup is just a spinning wheel.

**Comment by lukefretwell** [comment]
**Source**

LF

**Describe the bug**

When setting the linked images in the 'Gallery' widget to 'Lightbox', the lightbox on the public page just spins without opening the image.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to https://proudcity.com/gallery-widget/
2. Click on 'Edit page'
3. Click on edit gallery widget
4. Select 'Edit Gallery' button
5. Select 'Action on click' dropdown and select option
6. Select 'Done' and save page.
8. Refresh page and see error

**Expected behavior**

To see the image in the lightbox.

**Screenshots**

<img width="1110" alt="Screen Shot 2022-02-25 at 12 33 46 PM" src="https://user-images.githubusercontent.com/1569463/155802903-6a331020-ecb9-48e9-8567-db0011656abf.png">

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell I removed the double galleries that were showing due to adding Lightbox 2 here and then later rolling out WP Media Folder to everyone. They were both triggering the gallery.
