### ISSUE TITLE
Remove 'Find question' nav in service center

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1897]
> The “Find question” tab panel includes its own navigation tab panel that may cause confusion for some users. It unnecessarily duplicates the navigation choices available on the previous screen.

> Recommend removing this level of navigation to simplify the panel.

## Comments

Agree.

**Comment by jlyon** [comment]
Just to be clear, they want to remove this column.
![Screenshot - 2021-11-04T224739 195](https://user-images.githubusercontent.com/550909/140464510-85b3cdae-18dd-46b0-9d0a-cd0a616104cb.png)

So that it will look like this, correct?
<img width="980" alt="Screen Shot 2021-11-04 at 10 48 50 PM" src="https://user-images.githubusercontent.com/550909/140464522-75f946dc-1d55-49f3-ae68-d58c0ccd9852.png">

**Comment by kevindherman** [comment]
@jlyon I believe with the edit from https://github.com/proudcity/wp-proudcity/issues/1893 removing the right panel is correct.

@lukefretwell what do you think?

**Comment by lukefretwell** [comment]
@jlyon @kevindherman yes, looks much better.

**Comment by jlyon** [comment]
This change has been made and deployed platform-wide @kevindherman

**Comment by kevindherman** [comment]
@jlyon awesome.

Should this move to ready or be marked as done?
