### ISSUE TITLE
Multi-day event display in list view

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1944]
**Source**
Williams County

**Describe the bug**
Multi day events display correctly in calendar view but only behave as a single day event in list view. 

From Zendesk:

"For multi-day events, they show up properly on the Calendar view, but in the list view, the event only shows up for the first day. Same if you are viewing the event itself.

Noticed this because we are closed for two days over Thanksgiving. On our calendar (https://www.williamsnd.com/calendar) it shows a two day closure, but on the list view (https://www.williamsnd.com/calendar-list-view?pager=2&filter_categories%5B0%5D=264) it only shows a closure on the first day. On the event itself (https://www.williamsnd.com/event/thanksgiving-2022/) it also says it is only happening the one day.

Is there a way to be able to have it show up twice in the list or show that it is a two day event/closure?"

**Expected behavior**
We don't really have a solution for a multi-day event. It could either display as is but stays on the list until completed OR as the customer has suggested, list multiple times in the list for each day and then each one would roll off as the it passes.

**Comment by curtismchale** [comment]
It does appear that I can read the unix time stamp difference and if it's longer than 24 hours I can duplicate the event. I'll likely need to add some code to detect if it's more longer durations and then do some math to figure out how many times I should duplicate the event and which dates I'll need to pass to them so that they show up properly in the list.
