### ISSUE TITLE
webform file upload naming issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1974]
**Source**
Lucas, TX and the form they're testing is "City of Lucas Water/Trash/Recycling Service Application & Agreement"

**Describe the bug**
Files uploaded using webforms using the same file name are getting crossed up when viewing entries. 

From the customer:
Hello,

I just ran another test regarding this naming of attachments on applications and still received the same results regardless of whether or not the file is deleted. I ran one test where I submitted a file with an attachment titled “Animal” and it had a picture of a dog. I kept the application in the system and submitted another application with a file also titled “Animal” but with a picture of a cat. When the second file came in, the attachment shows the dog picture from the first application, not the cat picture from the second application. I ran another test where I did the same thing, but I moved the first file to the trash and then permanently deleted it from the system. The application had attachments with the same name and the second application still pulled up the pdf from the first application, not the second.

Having run multiple tests, the issue is present regardless of whether or not a file remains in the system or is deleted. There appears to be a clear issue regarding the naming of attachments that get uploaded to your servers. This could be an issue in the future if say one developer wants to submit a permit application and they attach a file titled “Home Plans”, and then another developer submits a permit application and they also title the file “Home Plans”. There is not always an option to speak with customers beforehand to tell them to title the files differently. For this issue, it is not really a work around security practices, this is more about fixing a clear glitch within the system. Submitted attachments cannot be titled the same or else you run into this glitch.

**Expected behavior**
Files uploaded, even with the same name should display within the entry submitted in the webform.

**Comment by kevindherman** [comment]
@jlyon @aschmoe I know past file upload on forms has come up in the past so if there is any info that would be helpful or worth checking into please post here.

**Comment by curtismchale** [comment]
Looking at stock WP configuration with the version of Gravity Forms we are using it **does** rename duplicate files so that they don't have the same name. So `file-1.jpg` would become `file-11.jpg` if it was using the same filename as another file already uploaded. 

That leads me to believe that we're dealing with an issue in Stateless that doesn't rename the files like WordPress does.

I *think* that we can modify `gform_handle_file_upload` found in `proud-gravityforms.php` to add to the filename and get a unique string to stop conflicts. Our best bet is likely to use `time()` as the only way we'd get a duplicate filename is if a bot was uploading files named the same within a second (since `time()` is UNIX timestamp which includes seconds).

@kevindherman I'm waiting on some documentation from @jlyon on running stateless locally so that I can finish testing this. The notes above are so that I don't have to dig in as much when I come back to this.

**Comment by kevindherman** [comment]
@curtismchale sounds good.

The customer that reported this is using enhanced search with their documents which may help in pulling on the stateless thread when you get into it.

**Comment by kevindherman** [comment]
@curtismchale here is another webform database issue that may help in exploring this issue: https://github.com/proudcity/wp-proudcity/issues/1887

**Comment by curtismchale** [comment]
@kevindherman so I can upload files locally now, but local environments seem to be doing something "different" than the beta or live sites. There is already code that should randomize the filenames, but it doesn't appear to be running on the beta site or on the Lucas TX site. 

I'll need to figure out why it's acting different between environments next and then come up with a proper solution.

**Comment by kevindherman** [comment]
@curtismchale thanks for the update. Godspeed.

**Comment by curtismchale** [comment]
@kevindherman so it seems that we should be able to turn on the "Cache Busting" feature of WP-Stateless and that will prepend some characters to the filename specifically to avoid the issues we're seeing with duplicate filenames and viewing a file.

Lucas TX and the Beta site have this toggle set by a constant, and I'm not sure how to change the constants so we'll need to talk to @jlyon or @aschmoe next week to get that changed and document how one does that for a single site in testing.

Then we'd need to roll this change in constant to any site that is having duplicate file issues, or just all of them so we don't see the problem again.

**Comment by kevindherman** [comment]
@curtismchale that's great. 

Hopefully it's a quick deploy once @jlyon and @aschmoe are back.

**Comment by curtismchale** [comment]
@kevindherman I've asked Jeff and Alex about this so we can move it forward. https://proudcity.slack.com/archives/C0AH683JQ/p1646764685368379

**Comment by curtismchale** [comment]
@kevindherman I've configured the Beta site so that it should NOT have duplicate file names. You can test this in Gravity Forms with this form: https://beta.proudcity.com/upload-test

Entries for that form are found here: https://beta.proudcity.com/wp-admin/admin.php?page=gf_entries&id=83

Please check over other media based workflows on the site as well so that we don't have any unintended consequences.

I'm talking to @jlyon and @aschmoe about how to change the constant on a single site.

For my notes:

- I commented out the gravitforms include in `wp-proud-core` so that we don't run our GF code with stateless. I'm still waiting to find out if there is any reason we have the code around since it's broken anyway.

**Comment by kevindherman** [comment]
@curtismchale tested the following and they call checked out: 

- viewed entries
- notification attachment
- export file link

I think this is good to go.
