### ISSUE TITLE
Using apostrophe in the alert bar adds a slash

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1975]
**Source**

Holyoke

**Describe the bug**

When you enter an apostrophe in the alert bar text (such as President's Day), a slash gets added before the apostrophe and this can't be edited out.

**To Reproduce**
1. Go to alert bar admin.
2. Add 'President's Day'
3. Save alert bar setting

**Screenshots**

![Screenshot 2022-02-18 at 07-45-35 Home - City of Holyoke](https://user-images.githubusercontent.com/1569463/154715184-9f8038ba-6a3a-4c18-a7b5-19fe3305b626.png)

**Comment by curtismchale** [comment]
@lukefretwell took a bit longer than I anticipated. See #1977 for what the "real" long term fix is for our forms.

This has 2 changes that are quick and dirty to stripslashes from the output (https://github.com/proudcity/wp-proud-core/commit/ceded8f984846bc6e0384010e41372e50fc11d95) and then to stripslashes from the internal form (https://github.com/proudcity/wp-proud-theme/commit/ac58a0d8596b709cb62e2a65f83be3ced56d3d96).

That resolves the issue with our escaping, but as I said in #1977 we do need to look at a revamp of the internal forms because we shouldn't be having issues like this.

**Comment by lukefretwell** [comment]
@curtismchale thank you!
