### ISSUE TITLE
Update Google Analytics per new changes

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2005]
**Source**

KH

**Is your feature request related to a problem? Please describe.**

From Google:

```
Prepare for the future with Google Analytics 4

Google Analytics 4 is our modern solution for supporting businesses across platforms while prioritizing user privacy. We will begin sunsetting Universal Analytics next year and encourage all users to migrate to Google Analytics 4 as soon as possible. Use the tips and best practices below to prepare for the transition and see what Google Analytics 4 can do for your business.

```
**What feature would you like to improve**

Google Analytics + ProudCity dashboard

**Additional context**

https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/?utm_medium=email&utm_source=newsletter&utm_campaign=march2022advanced&utm_content=en_us

**Comment by curtismchale** [comment]
We add the code to the pages here: https://github.com/proudcity/wp-proud-admin/blob/master/inc/tracking-code.php#L8

It's saved in a DB option by the name of `google_analytics_key`

Possible future solutions would be to move to a plugin to produce our key because they'll keep it up to date with the latest GA options and systems. [Monster Analytics](https://www.monsterinsights.com/) is the most popular one I'm aware of.

**Comment by kevindherman** [comment]
@curtismchale mentioned: https://usefathom.com/blog/google-analytics-importer

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell noting a GA email that came in to help with the transition:



Be ready for what's next with Google Analytics 4
--


Be ready for what's next with Google Analytics 4
 
Our next-generation measurement solution, Google Analytics 4, is replacing Universal Analytics. On July 1, 2023, Universal Analytics properties will stop processing new hits. [Read our latest blog post to learn more about the Universal Analytics turn down](https://notifications.google.com/g/p/APNL1TiwbZEOllG3dvigRN9RDG70d7qGGLD3Cc3MWhrSABSyTonnHDQQkbPGX_ar24MS8yCI9nOVJ63QFK6qcMbfsBnCKxL0kAZCd0s5iv9k0GHkGYgkUYQtMwrSBKGuwllN-3HIjGZCIfOMAc2vQGBjGcBwmZF-1m1sdl1p8IPkP793UGTQCvLguiJ_47tzefDRbHkfCIXvdFIG5vUtkV1PByUM6FySJSGgbnUukAMpq6_J_nhHQbV0OoRH2DvPUN2410PWqPuPyrX6Be2B6m76CvI535A616WfOAZDMy_MVsDsRWttWw6RmWcn-78N6EdbA0NF-8F9l_aiD_cII30QARzIe9YKjRz1ZEIZ1smcXhwDor-U6Q).
 
In preparation for the year ahead, we encourage you to complete your move to Google Analytics 4 as soon as possible. In order to build historical data and continuity in Google Analytics 4, it is essential to finish your setup. To start using Google Analytics 4 in place of Universal Analytics, we recommend you complete the relevant next steps from the below checklist:

**Comment by kevindherman** [comment]
This email is guidance to setup a new property ahead of analytics 4.

Subject: Create a new property ahead of Universal Analytics beginning turn down in 2023


Be ready for what's next with Google Analytics 4
--


Be ready for what's next with Google Analytics 4
 
Our next-generation measurement solution, Google Analytics 4, is replacing Universal Analytics. On July 1, 2023, Universal Analytics properties will stop processing new hits. [Read our latest blog post to learn more about the Universal Analytics turn down.](https://notifications.google.com/g/p/APNL1Tg-GzzuLTOG8nGRIKtN2_loGFAcbuKyu_LdBbK2refKi8RipTK-GW8xUFy6DZh9SPHwVSYLLXeKE38E5id_zd47tQwebcgpoqFC0qIP1kN5TlXkV-YcegdjK-aivMmjIaWIkXfWTVc6bxg28RlOKuPm34GeoJwpURWha5rfAcAbe7ZlM2Kff1vXiEtRG-ku2SHN1FdSIUFxrmzP3njh4yF4-bPlJ9CsogSvj-dfm7dMX9IYUgfzEycje7tnuZevEcAhv0PNNM_QnvnHqzyfg3qD-ZZXqxfUYSSPfSB18nTJz6ZFa_UdMbnRxyRKpwflBvhOkuvDsFrLdpL7bs4RhKHkNAX4L6YImDh1VFr9lSb3)
 
In preparation for the year ahead, we encourage you to start your move to Google Analytics 4 as soon as possible. In order to build sufficient historical data and continuity in Google Analytics, it is essential you create a new Google Analytics 4 property.
 
[SET UP GOOGLE ANALYTICS 4](https://notifications.google.com/g/p/APNL1TiSqQDcAhvwYzR-PFjyFLGv0XjqUrjdpy4wLxs4AiR7A6e3FbRf_qRDA1lTkxcYFtPP0G30z7W9ZkHw8koApurxOsnQS4hnnI-RGLGYoJ_wuKeYAav6WAi9rD6AQlhGSHHFWFzQRlUX4j10EbA5Q_si6bvKl73mpGm6sPHSl8-5knaXCsC4vtjgO1PZ9SNB-WHwthWu7nyQm7_Tpd389oYjnfQ8YJrk3H8jpN9kZM8ukjk0HgthKKO5gmFRo1RffOuaWM5Dpea7HzrUgGZUKHbV9lWCTCLRaGnh1spbd8yOtjRidkykuKwtkClpD1CL0tZc0-XQobzpLWmDpSb1zXf2rSzW)
 


For more information on how to get started with Google Analytics 4 you can check out our in-depth migration guide.
--


[For more information on how to get started with Google Analytics 4 you can check out our in-depth migration guide.](https://notifications.google.com/g/p/APNL1TiqQTXghziH4_GfZpe72zSSXibcpaqGAAlTEqO531HGb6ViZtEOxWajezP34JI0LeCX6e4XgzOHqMVwCDfyla-N7gfWvBL6yi7PJjxM1zQONh1QaaFN01ZWgnyBBsnoGWTEt6kDYqQTE87xtnI7PiTg08ixB6DdGZs2RM93oaXF0bAD7VpAa98BeMAWgho_zi7_l-A5O_2q8Uj06Atar6d8PiPlMb766g-rYe31YyD--6YSfNAGWh8Ljovcrohm0OBni8Z5KoI_aBesNi2LRD3K0irZtRCtSHifoSvkxg_5mUwRqi81qWqa1SMGJfegroLgxzTIt5c)
