### ISSUE TITLE
Remove news feed from location detail

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2051]
**Source**
Williams County: https://www.williamsnd.com/locations/northwest-youth-assessment-center/

**Describe the bug**
Location details (which are mostly hidden for end users) has a news feed on the right side that should be removed: https://www.williamsnd.com/locations/northwest-youth-assessment-center/

I went to remove from the widgets page but didn't see the option: https://www.williamsnd.com/wp-admin/widgets.php

**Additional context**
You can only see this location detail by viewing location from the dashboard or from a google search so it's pretty buried. Still, the news feed isn't needed.

**Comment by curtismchale** [comment]
@kevindherman there is no custom sidebar for the Location Custom Post Type (CPT). It's using the News Sidebar to populate the content on that page.

Do we need a custom sidebar for the single-location.php type so we can put custom content on it or do I just exclude the sidebar from all single-location.php content?

This change would apply across all sites since it's in our base theme.

I'd lean towards creating a custom template for location with it's own sidebar because it will increase flexibility of the sites long term.

**Comment by kevindherman** [comment]
@curtismchale What's the difference in level of effort?

This view of location content is generally hidden so it's not a high priority. If there's a big difference in the time to take to do a custom template vs just hiding it, then just hide it. If it's a similar effort then do the custom template route.

**Comment by curtismchale** [comment]
@kevindherman I'll just copy the existing template and change out the sidebar. Maybe 10% more work but far more flexible in the future.

I'll register a new sidebar as well, which is a couple lines of code.

Total time to do it is 30 minutes probably.

**Comment by kevindherman** [comment]
@curtismchale sounds good.

**Comment by curtismchale** [comment]
- [x] check what this does to the Petaluma base theme as it uses a different (custom) template but displays the same news in the sidebar
- [x] check the Santa Ana issue as well
