### ISSUE TITLE
WP Quick Menu is far out of date

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2057]
**Source**
Curtis

**Describe the bug**
[WP Quick Menu](https://wordpress.org/plugins/wp-quick-menu/) is 7 years old and out of date. @kevindherman @lukefretwell what are we using it for. We should look for a modern replacement if we're still using this functionality anywhere. Currently, it's got a bunch of errors in the code that fill our debug logs making it harder to find real issues.

**Comment by curtismchale** [comment]
Even worse, it's been mostly broken for 7 years. Variables to enable functions have been spelled wrong so they never existed ...

**Comment by curtismchale** [comment]
We have the plugin submitted to WP.org as we have a fork of it. We need to go through the updated security stuff so that we can launch it and move to it.

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell we discussed these in more detail on the call but here's feedback on updated menu in priority order:

- If a page is part of a menu and you move it to another, it doesn’t update on the front-end until you go into the advanced menu and remove the original menu.
- ability to change the menu label from the page interface (not linking to advance settings)
- Ability to create a nested item from the page (not linking to advance settings). It can just be two layers in and for more layers in they can opt into the advanced menu.
- Dashboard > menu link should go to advanced menu instead of the customizer

**Comment by kevindherman** [comment]
@curtismchale I got a report of the homepage linking issue from Cities Association this morning who got the menu update which is concerning.

I did notice this plugin error about the quick menu for them, could that be the issue:
![Screen Shot 2022-08-08 at 12 20 45 PM](https://user-images.githubusercontent.com/6032426/183465573-7e045736-f75c-492d-a16e-080d7dd7f805.png)

**Comment by kevindherman** [comment]
@curtismchale cities association didn't have draft or pending menus but did have this plugin issue.
