### ISSUE TITLE
Document the issue with getenv

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2064]
**Source**
Curtis

@jlyon can we document the issues we had "yesterday" with `wp-config.php` and the salts not working as expected.

Or at least link to the process in the current documents.

**Comment by jlyon** [comment]
The issue was that we were looking for ennvars like `AUTH_KEY` in wp-config.php, but they were defined with a `WORDPRESS_` prefix like `WORDPRESS_AUTH_KEY` in the deployments (https://console.cloud.google.com/kubernetes/deployment/us-central1-a/proudcity/test/beta/yaml/edit?authuser=1&project=proudcity-1184):
<img width="377" alt="Screen Shot 2022-06-25 at 8 58 50 AM" src="https://user-images.githubusercontent.com/550909/175781409-637375c0-0faf-4116-8fb0-6016d7ed93cf.png">.

This was the PR that fixed it @curtismchale https://github.com/proudcity/wp-proudcity/commit/59108399385261eb99f6aac67379b65fb146bf5d
