### ISSUE TITLE
Default featured image

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2092]
**Source**

LF

**What feature would you like to improve**

Featured image for all content types.

**Describe the solution you'd like**

Would be great to have a default featured image for the meta image tag.

`<meta property="og:image" content="https://storage.googleapis.com/proudcity/alpha/uploads/2019/01/favicon.png" />`

Ideally, this would be managed in the customize tool under 'Site Identity' with same functionality as 'Site Icon'.

* Section title: Featured Image
* Description: The default featured image displays for all content types when you don't have one. This image is good for bringing visibility to social media posts. Recommended dimensions: 512x512 pixels

**Comment by curtismchale** [comment]
@lukefretwell based on [this site](https://ahrefs.com/blog/open-graph-meta-tags/) we should be aiming for 1200x630 for the image. Ultimately, it's up to the end user what they put there but I do have some text in telling them to aim for 512x512. Shall I leave it that way?

Otherwise, this is rolled out to the sites at this time.
![CleanShot 2022-11-24 at 13 49 04@2x](https://user-images.githubusercontent.com/74561/203867236-642e84fd-e15f-432b-b3c2-9b4f59dedd77.png)
