### ISSUE TITLE
'Display first teaser at the top' bug

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2148]
**Source**

Montgomery, OH

**Describe the bug**

> We can't get the featured image to show up on the first news and event lists on the homepage. Both have a featured image set.
> Link to page with this issue
> https://www.montgomeryohio.gov/
> 

From KH:

> the ticket from Montgomery this morning does appear to be a bug. I think it comes from cleaning up the mini list display option. Previously if you selected “display first teaser at the top” it would provide more information and the featured image for just the top post. Everything else would be a limited view. this might be a quick thing to allow for that featured image to display as the first item again if that box is selected, even for mini list display.

**Comment by curtismchale** [comment]
@lukefretwell 

It was a CSS bug with "fancy" math instead of just putting the results of the math in the CSS.

Tagged theme in build: https://github.com/proudcity/wp-proudcity/commit/652c9189f53fd71c03d8a3cc378a76d90fcb7194
Changes in PC patterns line 39 and the following ones that also had math in them: https://github.com/proudcity/proudcity-patterns/commit/5b27049cc87aa800f6236c5af01edab63769075c

This is currently deployed on our PHP 8 branch so is not rolling out to everyone. Will roll out to everyone once #2124 is rolled out.
