### ISSUE TITLE
Issues content found by search results bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2149]
**Source**
The source of the issue support ticket 6185. In troubleshooting I'm using Marin DPW and Mount Pocono. 

**Describe the bug**
Report an issue content has loading issues when user navigates to content from search results page.

**To Reproduce**
Select issue from search results: https://publicworks.marincounty.org/search-site/?term=street#/city/report/embed/blocked-roadway-in-marin

Navigate to https://publicworks.marincounty.org/issues/traffic-or-street-light-malfunctions/ and page loads without service center blinking. 

For Mount Pocono:

If you go to a search results for pot hole: https://mountpocono-pa.gov/search-site/?term=pot+hole#/city/report/embed/pot-hole

And select pot hole issue: it redirects to the demo site and has a completely different URL path than DPW (which is the standard: https://demo.proudcity.com/?post_type=issue&p=3369

**Expected behavior**
It should behave like DPW is but without the load issues blinking. 

**Screenshots**
https://publicworks.marincounty.org/issues/traffic-or-street-light-malfunctions/
![Screen Shot 2022-12-05 at 5 55 56 PM](https://user-images.githubusercontent.com/6032426/205760835-4b848e8d-ceb3-449c-9dd4-8be0dd7103a2.png)

**Additional context**

**Comment by curtismchale** [comment]
@kevindherman the issue with Mount Pocono was that the URL in the database was set to city template still. I tried a bunch of things but ended up needing to change that value manually. If we have other issues I can change it for the whole site but I only did it for one page at this time.

For Marin DPW...when you choose custom text the site defaults to some JavaScript that looks up a URL in the post metadata  and then tries to redirect the user to that URL. This code path should only be an option if someone chooses `External Link` but currently it's the default option if no other matches are made. In this case the `url` field was blank and thus it got stuck redirecting itself to itself.

I've changed it so that we only try to redirect to our custom link `if` we have actually selected external link. Otherwise we'll never see it.

This fix is currently behind our PHP 8 upgrade in #2124 though I've manually rolled it out to Marin DPW so they see the fix now. Everyone else will get it once we deploy the PHP 8 upgrade.

**Comment by kevindherman** [comment]
@curtismchale awesome. I'll keep an eye out for other city template links but everything else sounds great!

**Comment by kevindherman** [comment]
@curtismchale thanks for this.

For DPW, this likely happened in that it was originally created as a custom link and then changed to custom text. Your solution makes sense to me moving forward.

I'll keep an eye out for the city-template links, I feel like I have seen that but can't remember when or where.
