### ISSUE TITLE
Media list display should only show featured image and title.

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2151]

**Comment by curtismchale** [comment]
When we made changes in #2129 the side effect is that some type of description is always display. Previously the users had no access to `the_excerpt` so the post display was simply titles without any type of description.

Now we need to add a checkbox so that users can choose to display `the_excerpt` if they want.

**Comment by kevindherman** [comment]
@curtismchale would this mean that the default would be no display or that customer would need to make the adjust to display how it was previously?

**Comment by curtismchale** [comment]
@kevindherman no I'd default to NOT show it since that was the previous functionality and should require no interaction from users.

**Comment by kevindherman** [comment]
@curtismchale perfect.

**Comment by curtismchale** [comment]
Added the option to hide teasers or show them on teasers with the media list option: https://github.com/proudcity/wp-proud-core/commit/df6bb48d27bff775d5c381cd69919322fb4e9591
New deploy: https://github.com/proudcity/wp-proudcity/commit/0359bda3e809019b4846d351eb74248acd26240a

**Comment by curtismchale** [comment]
@lukefretwell if you want to achieve the look we had earlier with the media list select it and then choose to show the excerpt.
![CleanShot 2022-12-14 at 13 26 31@2x](https://user-images.githubusercontent.com/74561/207718362-95aa10b9-e947-4d4a-a523-5e70079066ce.png)
