### ISSUE TITLE
Sitemap error

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2171]
**Source**

LF

**Describe the bug**

The Petaluma sitemap page is throwing errors:

* Front-end getting error `There has been a critical error on this website.`
* When trying to edit/trash page, get  `There has been a critical error on this website. Please check your site admin email inbox for instructions.`

Page: 
**To Reproduce**
1. Go to Petaluma site map: https://cityofpetaluma.org/sitemap
2. Try to edit page
3. See error

**Expected behavior**

Sitemap would display with no errors.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Can't replicate this issue on city template or proudcity.com. Appears to be isolated to this site.

**Comment by curtismchale** [comment]
@lukefretwell Part of the issue seems to stem from invalid menu items. This is content that is in the trash, but still in a menu. I've deleted them from the menus on Petaluma and documented the items below.

**Airport menu**
<img width="717" alt="CleanShot 2023-02-15 at 08 00 27@2x" src="https://user-images.githubusercontent.com/74561/219082748-4b394610-1a2e-417e-8931-4cfe9be19247.png">

**[City Permits](https://cityofpetaluma.org/wp-admin/nav-menus.php?action=edit&menu=325)**
<img width="697" alt="CleanShot 2023-02-15 at 09 32 38@2x" src="https://user-images.githubusercontent.com/74561/219107773-5d6f7fff-2dc8-4585-91c3-59f267f6f0f5.png">

**[Economic Development](https://cityofpetaluma.org/wp-admin/nav-menus.php?action=edit&menu=70)**
<img width="801" alt="CleanShot 2023-02-15 at 09 36 50@2x" src="https://user-images.githubusercontent.com/74561/219108650-a891f869-9503-4f4d-a415-7b1860aa3921.png">

This gets me further through the code but there are other issues I'm still tracking down.

**Comment by kevindherman** [comment]
@curtismchale is a reason why deleted pages are sometimes, but not always removed from the menu? It would be great if menus were deleted when pages are. The invalid menus has thrown off other things that come up in support.

**Comment by curtismchale** [comment]
@lukefretwell Second set of issues is that some menu items had themselves as parents so it all went into a loop where they kept looking for themselves as the next level parent.

@kevindherman It could happen if a user was deleted from the site and they created the pages. 

From reading, if a page is still in the trash then it doesn't get removed from a menu. If you empty the trash it does get removed from the menu.

I'm not sure how to test this as some of the issue was related to bad data on the site in question. I've pushed the current build of sitemap functions up to Beta. Take a look and make sure that it functions as intended and then I can deploy it to other sites.

**Comment by kevindherman** [comment]
re: invalid items, that makes sense to what's happening.

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell I'm looking for approval to push this out today.

**Comment by kevindherman** [comment]
@curtismchale this sounds good to me but just want to double check on the plan for fixing Petaluma's menus so that it doesn't break the sitemap. Is that something you did or we need to do?

I'm seeing the same issue on https://www.ketteringoh.org/ and https://www.playkettering.org/

So whatever is being done for Petaluma cleanup I'd like to include these two sites as well.

**Comment by curtismchale** [comment]
@kevindherman I did it live as I found the issues.

I'll have to look at the menus for the other sites and see if it's just invalid items or if it's actually issues with bad data in the items.

I can do that after deploy though.

**Comment by curtismchale** [comment]
Deployed with: https://github.com/proudcity/proud-recipes/releases/tag/2023.02.20.1212

I went through the Kettering sites and saved the menus to clear out the recursive parent issue and verified that the sitemaps now work.
