### ISSUE TITLE
Page showing outside of theme template

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2190]
**Source**

* https://proudcity.zendesk.com/agent/tickets/6257
* https://proudcity.zendesk.com/agent/tickets/6284

**Describe the bug**

Some pages are displaying outside of the theme template:

* Somewhat broken
* Admin bar doesn't show when logged in

Examples:

* https://www.townoffairfax.org/community-classes-events/
* https://www.townoffairfax.org/meetings/town-council-meeting-june-1-2022/
* https://madeirabeachfl.gov/elections/

**To Reproduce**
1. Go to https://www.townoffairfax.org/community-classes-events/
2. See error

**Expected behavior**

Should be in theme template.

**Screenshots**

![Screenshot 2023-01-26 at 12-12-27 Community Classes   Events - Town of Fairfax](https://user-images.githubusercontent.com/1569463/214940501-42aba21f-bd57-4135-8876-3205703ba073.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

May be related to #2171

**Comment by kevindherman** [comment]
I added the Madeira Beach example above as well in case those others get updated: https://madeirabeachfl.gov/elections/

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell I just added another support ticket to the description. Here's the page in question: https://madeirabeachfl.gov/community-development-documents/

**Comment by kevindherman** [comment]
A few more details I'm noticing for the community development page: https://madeirabeachfl.gov/community-development-documents/
<img width="1410" alt="Screen Shot 2023-02-07 at 3 17 06 PM" src="https://user-images.githubusercontent.com/6032426/217355819-3c0e405d-375b-4ff4-b5ff-cd6b8dfa4e44.png">


In order to view the edit page you have to go through the dashboard: dashboard > pages > find the page > edit
Pages, the item shows site origin/pagebuilder: https://madeirabeachfl.gov/wp-admin/edit.php?s=development+documents&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&paged=1&action2=-1
<img width="1187" alt="Screen Shot 2023-02-07 at 3 16 53 PM" src="https://user-images.githubusercontent.com/6032426/217355574-8375f682-0cdf-4b84-bbb5-b67e98bc737b.png">

Edit page: https://madeirabeachfl.gov/wp-admin/post.php?post=4240&action=edit
The pagebuilder option has disappeared:
<img width="1422" alt="Screen Shot 2023-02-07 at 3 16 41 PM" src="https://user-images.githubusercontent.com/6032426/217355650-2ea12834-05db-4726-bc77-da1611669825.png">

**Comment by lukefretwell** [comment]
Beta page works for me @curtismchale @kevindherman .
