### ISSUE TITLE
Watch Gravity forms ticket

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#226]
Using the default gravity forms widget field totally breaks page when using more advanced fields.  

Need to find way to output the shortcode inside pagebuilder.

**Comment by aschmoe** [comment]
see #225

**Comment by aschmoe** [comment]
-[ ] Hide normal gravity forms widget from options

**Comment by kevindherman** [comment]
Is this a blocker to showing Erika tomorrow?

**Comment by aschmoe** [comment]
@kevindherman not anymore :)

**Comment by kevindherman** [comment]
@aschmoe the name of the widget is now called "missing widget" instead of forms on the test page I setup for my call with WC this morning. Can you give it another name?

https://www.westcarrollton.org/wp-admin/post.php?post=3484&action=edit

![screenshot 2016-03-14 12 53 02](https://cloud.githubusercontent.com/assets/6032426/13752178/e9f9f328-e9e3-11e5-9fa6-1250d33f5360.png)

**Comment by aschmoe** [comment]
@kevindherman this is done

**Comment by kevindherman** [comment]
Looks good.

**Comment by jlyon** [comment]
# Leaving open to monitor https://siteorigin.com/thread/issue-with-page-builder-gravity-forms-pagination/
