### ISSUE TITLE
Standard width displaying as full width

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2270]
https://cityofpalmview.com/

Standard width is displaying as full width.
![Screen Shot 2023-06-12 at 5 39 59 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/bb6489d4-ab4c-45d0-93a3-5c6dce874b2b)

Should look like:
![Screen Shot 2023-06-12 at 5 40 36 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/67903034-6ba2-45ba-b359-d7770d8b0e7f)

I checked the rows on the homepage to see if they customized a wide view but the rows are set to standard:
![Screen Shot 2023-06-12 at 5 41 56 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/e261a273-7c0c-49c4-9833-c473047ec440)

There also isn't any custom CSS so I'm not sure why this is happening @curtismchale @lukefretwell

**Comment by curtismchale** [comment]
The issue is that they use the TextMyGov widget which targets the generic `.container` class. Since TextMyGov uses `.brz` to wrap all the HTML for itself the widget should really use `.brz .container` and make sure that all CSS is prefixed with `.brz` so that it doesn't interfere with our sites, and I can only assume other customer sites that use this.
