### ISSUE TITLE
Script menu standardization

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2302]
## Source

* https://proudcity.zendesk.com/agent/tickets/6518

## Describe the bug

The redirect tool is not available on some sites.

## To reproduce
1. Go to source ticket to locate site.
2. Login to admin.
3. See error

## Expected behavior

To see the redirect tool.

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
@curtismchale  Lucas, TX is having the menu editor/redirect issue that Montclair was: https://www.lucastexas.us/wp-admin/admin.php?page=proud_dashboard#/sites/lucastx/dashboard

**Comment by curtismchale** [comment]
After looking at scripting the update to the `wp_options` table for this field it turns out the value is over 10k lines long and that it won't run on our servers. I tried a few different methods to modify the query and run it anyway but was having little success.

[We decided to drop the scripted update to all menus at this time](https://proudcity.slack.com/archives/C04MEBVAV2L/p1690322481891909?thread_ts=1689741924.079229&cid=C04MEBVAV2L). We updated the sites that needed it manually and will move forward at some point with hardcoding the admin menu and removing WP Admin Menu: https://github.com/proudcity/wp-proudcity/issues/2315
