### ISSUE TITLE
Move advanced menu admin lower

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2329]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

LF

**Is your feature request related to a problem? Please describe.**

The advanced menu in the right side admin takes up a lot of space at the top. You have to scroll down everytime you want to save the page and the 'Publish' box should be more accessible when managing pages as it's the action users use most often. 

**What feature would you like to improve**
A clear and concise description of the current feature.

Right admin sidebar

**Describe the solution you'd like**

Move advanced menu lower ideally below featured image box.

**Additional context**

**Comment by curtismchale** [comment]
@lukefretwell 

Changing this has some nuance.

First, we can set it, but if a user drags the editing box on the page to a new location then that is the new location. Since we share some users if I drag it as one of our shared users you will see it in any position I have moved it to. This user settings is per site and per user so you may see different position of metaboxes on different sites. When we check this it's worth checking a few sites to see if it's the same on all sites or if the metaboxes move around. If they move around someone moved them at some point.

Second, there are only a few "levels" of priority for `metaboxes` in WordPress. We declare nothing so it's set to `default` which means that the metabox is placed on the page in the standard priority, but then it may be lower than other `default` metaboxes if their plugin loads them earlier. My other settings in order of how important they are:
- `high` - highest and more "important" than core metaboxes.
- `core` - WP standard priority for it's metaboxes
- `default` - when you define nothing or set it to this
- `low` - appears lower on the page

**Comment by curtismchale** [comment]
We discussed this and it works as it should so we wont be fixing this specific item at this time.
