### ISSUE TITLE
Second accordion on a page doesn't collapse as expected

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2352]
**Builds**

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/b2830bd5-e7cb-4f83-ad32-a6b500e77e68?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/7c8facf5-cdd4-47b2-bebb-c29d1a46dfc2?project=proudcity-1184)

## Source
https://belvedere-ca.proudcity.com/get-started-on-a-home-project/

## Describe the bug
The second set of accordions on the page does not automatically collapse a previously expanded item like the first accordion does higher on the page. 

## To reproduce
1. Go to https://belvedere-ca.proudcity.com/get-started-on-a-home-project/
3. Scroll down to second accordion 
4. Click first option
5. Click second option
6. See the first option stays expanded

## Expected behavior

If you follow the same steps above but on the first accordion, you'll see the expected behavior or opening and closing when new options are selected. 

## Screenshots
![Screen Shot 2023-09-07 at 3 48 03 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/d0cb9e3b-5d8f-481e-8006-dc512a332070)

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
The issue was that a Bootstrap 3 accordion expects a unique ID for each accordion so that the child items can associate themselves with the proper parent. Our second accordion was failing to close items as expected because we had attached everything to a generic `#accordion` value which mean the second one was trying to operate on the first accordion and the JS was getting messed up.

A build is in progress.

See notes: https://github.com/proudcity/developers/blob/main/Github%20Issue%20Notes/2352%20-%20Double%20Accordion.md

**Comment by curtismchale** [comment]
Released: https://github.com/proudcity/wp-proudcity/releases/tag/2023.12.18.0602
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2023.12.18.0602
