### ISSUE TITLE
Event location error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2384]
## Source
https://willamina-or.proudcity.com/

## Describe the bug
Unable to save event location when creating or editing an event. After entering event location information and saving, the event self-selects "this event has no location" option. Also unable to select preexisting event because the dropdown doesn't open to display event location options. 

## To reproduce
1. events
2. add new
3. enter location 
4. save
5. see error
Can do the same when exiting existing event.

## Expected behavior
Should get google map options or enter your own.

## Screenshots
![Screen Shot 2023-09-28 at 2 57 03 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/664d0e92-9a83-4d2e-b01f-4eb5c66c1618)

## Additional context
@curtismchale it seems like google maps isn't connecting so I'm wondering if that's the first place to look.

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
@curtismchale meetings content pulls from the content type "Proud location" and works. 

See Somerville meeting working: https://somerville-nj.proudcity.com/meetings/borough-council-meeting-january-17-2023/
and the location: https://somerville-nj.proudcity.com/wp-admin/edit.php?post_type=proud_location

However, event location does not work but uses similar google maps tools: https://somerville-nj.proudcity.com/wp-admin/post-new.php?post_type=location

I did notice that the event location address fields are below the text description on the event (not working) but above the description on location (working). I was not able to drag the text description in the now working event location and could in the working location. Perhaps there's something with the text description field that's at the root of this.

**Comment by curtismchale** [comment]
@kevindherman the location of the events fields has no bearing on this issue. You can't drag around the editor for [events](https://willamina-or.proudcity.com/wp-admin/edit.php?post_type=event) because it's the stock WP editor that comes with a custom post type, and this is not something you can move around. You can't move it around on posts/pages either.

Remember from https://github.com/proudcity/wp-proudcity/issues/2112#issuecomment-1275063707 to save a new location you must give it a title. I was able to create a new location and get a title for it.

I did add a Google maps key [here](https://willamina-or.proudcity.com/wp-admin/edit.php?post_type=event&page=events-manager-options#general) for our test environments and added it to City Template so that it moves forward with new installs.

We should add a line in the Trello launch card that reminds me to change to the `prod` Google Maps key when we launch a site. It would go under the existing one for adding the Google API key.

**Comment by kevindherman** [comment]
@curtismchale thanks for the reminder, that helped.

Still, when I go to add a new event or edit an existing one, I am not able to use the event location dropdown to select existing event locations. If you click the dropdown nothing expands.

**Comment by curtismchale** [comment]
It's not really a dropdown. As in the HTML is not a `<select>` element it's a text `<input>` element. They have some CSS class on it called `selectize-input` which appears to come from [this JavaScript library](https://shiny.posit.co/r/articles/build/selectize/) and makes the input look like a dropdown/select.

So you have to type a portion of the location name into the input field and then it will populate available options for locations that can be filled in for you.

![CleanShot 2023-10-04 at 09 43 00](https://github.com/proudcity/wp-proudcity/assets/74561/003b0b2f-2ca3-4c0a-b12d-ecedd63c4165)

Yes this is bad UI. I [reported bad UI 11 months ago](https://wordpress.org/support/topic/little-user-feedback-is-provided-if-you-dont-name-a-location/#new-topic-0) and have had no response. I have also [reported](https://wordpress.org/support/?post_type=topic&p=17100135#new-topic-0) this UI confustion but given the fact that we have no response in 11 months and nothing has changed in the UI I don't hold out much hope of getting any response.

So we need to educate ourselves and our users on how this works. Yes it confused me as well.

This confusion has come up before here: https://github.com/proudcity/wp-proudcity/issues/2293

## Possible real solutions

- fork plugin and create better interactions
- attempt to write our own extra code that interacts with this plugin and presents UI tips when users are attempting to click the dropdown, or save a new location from https://github.com/proudcity/wp-proudcity/issues/2112#issuecomment-1275063707

If we want to do either of those two options we should create a new issue.
