### ISSUE TITLE
Gravity Forms Constant Contact plugin login bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2467]
## Source
https://www.baysidewi.gov/

* [LINK TO SUPPORT TICKET](https://proudcity.zendesk.com/agent/tickets/6738) 

## Describe the bug
With verified Constant Contact credentials (logged in directly to Constant Contact), the username/password fields doesn't accept the credentials and gives a "The username and password combo provided is not valid". 

## To reproduce
1. Go to gravity forms constant contact plugin settings: https://www.baysidewi.gov/wp-admin/admin.php?page=gf_settings&subview=gravity-forms-constant-contact
2. Enter credentials 

## Expected behavior
Should be able to login to hook Gravity Forms into Constant Contact. 

## Screenshots
![Screen Shot 2024-01-22 at 1 44 55 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/c83e1abb-115e-4ec5-b56f-a90091f0d45c)

## Desktop (please complete the following information):
 - Chrome > incognito and logged in.

**Comment by curtismchale** [comment]
@kevindherman 

The bayside CC plugin is **not** the official one. We're using one from [Katz](https://katz.co/plugins/gravity-forms-constant-contact/) and while they are well known, they haven't updated the plugin since 2018 so I'd assume it no longer works due to changes in how connections are made for Constant Contact

 I can't log in to the customer Constant Contact account as it requires 2FA and I have no way of getting that response. The new plugin requires an API key and App Secret, [you can find directions here](https://docs.gravityforms.com/constant-contact-add-on/) for setting it up. If they want us to do it for them we need [access to their account](https://knowledgebase.constantcontact.com/email-digital-marketing/tutorials/KnowledgeBase/41605-How-to-give-access-to-your-Constant-Contact-account?lang=en_US).
