### ISSUE TITLE
Fields to customer local services not displaying in service center settings

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2485]
## Source

* [Support ticket](https://proudcity.zendesk.com/agent/tickets/6783) This is unique to this customer who likely deleted all the local service options, 

## Describe the bug
In service center settings, all of the local services were removed. When you go to add new, there are no fields to input information. 

## To reproduce
1. Go to 'service center settings
2. Click add another under local services
3. Click on "local services 1" and options should expand but nothing is available. 

## Expected behavior
View service center settings on city template or any other site and you'll see field options when you select add another. 

## Screenshots
No fields
![Screen Shot 2024-02-15 at 5 03 00 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/9c31237c-d9c1-4477-954d-c2398f757025)

Expected view:
![Screen Shot 2024-02-15 at 5 03 11 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/32bd9eaf-1109-4e23-b5c5-78c5c5b41de2)

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@kevindherman the issue is that we don't deal with **no** values in the local services settings. This means if a customer deletes everything and saves without adding in the Local Service they want then we get to the state this site is in. We have 2 options.

1. I can just fill in a default value I grab from City Template, then they can change it all to be what they want. 10-20 minute job
2. I can dig into the form code and make it work if there are no values at all. (few hours)

It really should work the 2nd way, but given that we're talking about rebuilding parts of the service center I wonder if it's worth putting a bunch of work into it right now.

**Comment by kevindherman** [comment]
@curtismchale if you do option one will the ability to add more fields come back? If yes, that works. 

I think just putting in the standard city hall location information like this example: https://www.willaminaoregon.gov/services/#/city/local/address

But use the location and hours from Bayside:  https://www.baysidewi.gov/contact/

That should get it started to then see if we can add fields for the other stuff, right?

**Comment by curtismchale** [comment]
@kevindherman yes they will be able to change and add as much as they want after. I'll add that stuff in a bit.

**Comment by curtismchale** [comment]
@kevindherman this has been added and we can change things as well. I'll update Zendesk now.

**Comment by kevindherman** [comment]
@curtismchale thank you. Looks good.
