### ISSUE TITLE
WC: Finance page down

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#280]
I can confirm this. Screenshot attached from Chrome.

The "edit page" option is also missing from the admin bar.

I checked the other departments and they're not having the same issues so this is unique to Finance and Tax Dept: https://www.westcarrollton.org/departments/finance/

**Comment by kevindherman** [comment]
![screenshot 2016-04-06 10 44 27](https://cloud.githubusercontent.com/assets/6032426/14320961/31d186d0-fbe5-11e5-9b08-66ac2401bbfc.png)

**Comment by jlyon** [comment]
@kevindherman @aschmoe The problem was with the rewrite rules.  It looks like it was caused by the deployment, or something that happened after it (because /departments/finance worked in the backup db dump taken right before the deployment.

I added 
```
wp --allow-root rewrite flush
```
to the end of the deployment script.

Links:
* http://shibashake.com/wordpress-theme/how-to-flush-permalink-rules-with-flush_rules
* http://wp-cli.org/commands/rewrite/flush/
