### ISSUE TITLE
WM: Locations on showing on services map

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#332]
New locations that Jill is adding to the West Mead services map aren't showing. 

For example the Township Office and Roads Department is added and  has a category but isn't showing on the map.

**Comment by kevindherman** [comment]
![screenshot 2016-05-04 18 04 04](https://cloud.githubusercontent.com/assets/6032426/15033721/cfe4458a-1222-11e6-9cbe-42561aa69846.png)

Google maps:
https://goo.gl/maps/1EnAhTi8x7J2

frontend:
![screenshot 2016-05-04 18 06 06](https://cloud.githubusercontent.com/assets/6032426/15033724/e7f3b340-1222-11e6-9221-e1073cc6586d.png)

**Comment by jlyon** [comment]
Sorry, I think I missed a step when I told you the setup instructions.  In order to switch from the Foursquare locations to, you need to edit the map widget and set it to use Foursquare.  Then check all of the layers that shoud be included.

![screenshot from 2016-05-09 14 16 50](https://cloud.githubusercontent.com/assets/550909/15128586/77d47874-15f1-11e6-8184-5930801e4c03.png)

**Comment by kevindherman** [comment]
@jlyon Thanks, this is done.
