### ISSUE TITLE
WM: agency switch from linking out to single page still links out

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#347]
https://west-mead-pa.proudcity.com/govenment/

The Fire Dept used to link out but we switched it to be a single page format. However, it still links out. How can I get it to stop linking out?

![screenshot 2016-05-10 12 18 26](https://cloud.githubusercontent.com/assets/6032426/15153960/58e45c78-16a9-11e6-9a6f-112c64b14ab5.png)

If you click on the permalink the actual page comes up: 
https://west-mead-pa.proudcity.com/departments/fire-departments/

**Comment by jlyon** [comment]
We were using the external link if any url was set (even if the agency type was single page or section). Furthermore, you couldn't reset the url because it wouldn't save if the value was set to "".

I fixed the issue on WM by manually deleting the url value.

I fixed the issue on the platform by
1) Only using the external link if the agency type = External link
2) Allowing the url value to be deleted.
These updates will be pushed in the next release.
