### ISSUE TITLE
Different pins for local businesses map

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#362]
Is there a way for WM to select different types of icons for their local businesses map? 

I think it would help that map look nicer and we can promote the tactic to other customers.

**Comment by jlyon** [comment]
@aschmoe wanna take a crack at this one maybe?  Currently, we're hardcoding the icon based on a text search in the map js directive (or is it a route, I can't remember?).  It would be great to add a term metabox, but it might be more effort than  it's worth http://themehybrid.com/weblog/introduction-to-wordpress-term-meta.

Might be difficult because I think it's using Maki icons instead of Font Awesome currently.  As a short-term fix, it might be better to just match icons to the text used in the WM  map laters...

**Comment by kevindherman** [comment]
Not sure if it's actually easier but even being able to select pin colors
could be sufficient if icons will take a lot of effort.

On Fri, May 20, 2016 at 1:17 AM, Jeff Lyon <notifications@github.com> wrote:

> @aschmoe <https://github.com/aschmoe> wanna take a crack at this one
> maybe? Currently, we're hardcoding the icon based on a text search in the
> map js directive (or is it a route, I can't remember?). It would be great
> to add a term metabox, but it might be more effort than it's worth
> http://themehybrid.com/weblog/introduction-to-wordpress-term-meta.
>
> Might be difficult because I think it's using Maki icons instead of Font
> Awesome currently. As a short-term fix, it might be better to just match
> icons to the text used in the WM map laters...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/362#issuecomment-220519244>
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
Taxonomy metabox: http://wordpress.stackexchange.com/questions/211703/need-a-simple-but-complete-example-of-adding-metabox-to-taxonomy

**Comment by jlyon** [comment]
Part of #68
