### ISSUE TITLE
WA: search results pulling legacy content

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#387]
"If you click on the search in the top right corner (not the blue bar) and type in “police” I am seeing some really strange returns.  Scroll down in the returns and you will see the attached image.  It lists contacts that are not on our site anywhere that I can find.  Below that it lists another search return for “Jobs”.  Several jobs are listed there that are not included on our site."

![contactsearch](https://cloud.githubusercontent.com/assets/6032426/15610605/2023580a-23f4-11e6-9c6e-35f0d02a68b1.jpg)

**Comment by aschmoe** [comment]
@kevindherman , yeah there is something funky about how the content of the post was being created (some sort of caching mechanism).

I've made it so that search results will pull the yoast SEO description first.  This is probably smarter for search items in general and definitely will help SEO, so we should be working this into our training.

![edit page city of warr acres wordpress](https://cloud.githubusercontent.com/assets/1634686/15727966/8a220ff8-280e-11e6-9973-77d3b99e6eb1.png)
