### ISSUE TITLE
Remove wrench icon

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#405]
Remove wrench icon linking to issues in main nav.

**Comment by jlyon** [comment]
Fixed. @aschmoe added a fix so that if you select External link and leave the two url fields blank on https://warr-acres-ok.proudcity.com/wp-admin/admin.php?page=integrations, the two issues tab will be hidden from the actions box widget (it looks like this is hidden on WA), and from the topnav.

![screenshot from 2016-06-01 20 49 48](https://cloud.githubusercontent.com/assets/550909/15733409/8a8bb7f6-283a-11e6-8a4a-56a423cf2238.png)

**Comment by jlyon** [comment]
Wrench icon is hidden from topnav if External Link is selected for 311 service and the Issue URLs are left blank
