### ISSUE TITLE
Agency: Add "Do not display in lists" option

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#499]
Header and section link that's available on /residents and agency pages:

![screenshot 2016-09-08 17 23 47](https://cloud.githubusercontent.com/assets/6032426/18367476/4e330f78-75e9-11e6-81ba-c95c0dce1626.png)

Would be great to enable that option on sub menu pages that aren't one of the custom landing pages or agencies like https://san-rafael-ca.proudcity.com/commuter-information/ which is a sub menu page of https://san-rafael-ca.proudcity.com/smart/

![screenshot 2016-09-08 17 23 20](https://cloud.githubusercontent.com/assets/6032426/18367504/83b587ac-75e9-11e6-91fe-3f2bb022b47f.png)

The strategy here is that pages like SMART are important initiatives that they don't want to bury in an agency.

**Comment by jlyon** [comment]
Add a toggle to Agency Pages to appear/not appear in list.

**Comment by jlyon** [comment]
@kevindherman I thought of a "kind of hacky" way to do this that I set up on SR: create a new Agency, but leave it in Draft mode.  The Agency won't appear on /government, and the title and subnav is automatically added to all subpages.

I created a Draft SMART agency: https://san-rafael-ca.proudcity.com/wp-admin/post.php?post=5200&action=edit.  The top title and sidebar are appearing on all subpages now.  I had to go through and edit the pages to remove the submenu widget (I also changed a page back to a normal page since it no longer needed widgets).

If we think that these "Unofficial agencies" will come up a lot in the future on other sites, we can come up with a more elegant solution, like a "Show in lists" checkbox (note to self: see show-in-lists branch on wp-proud-agency).

cc: @aschmoe

**Comment by jlyon** [comment]
Does this make sense @kevindherman ?

**Comment by kevindherman** [comment]
@jlyon this does make sense for now but something cleaner should be set up in the future.

**Comment by jlyon** [comment]
we decided we wanted this on the dev call today

**Comment by kevindherman** [comment]
@jlyon we discovered that the hack using draft isn't actually working. The draft version displays for editors but anon. users get page not found.

This item should be prioritized next week.

**Comment by jlyon** [comment]
@kevindherman I added a new Exclude from Department lists checkbox to the Agency edit page.

Follow the previous steps, but publish the agency and check this box.  I did this for SMART.

**Comment by kevindherman** [comment]
@jlyon perfect. I will pass along.
