### ISSUE TITLE
Allow non-email addresses for Agency contact field

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#514]

**Comment by jlyon** [comment]
@kevindherman If you enter a link instead of an email address in the (now renamed) "Contact email or form" field on a Department, the link will appear as "Contact" with an arrow icon.  Otherwise you will get the standard "Email" link.

![screenshot from 2016-09-16 14 58 56](https://cloud.githubusercontent.com/assets/550909/18602458/1af8aa06-7c1e-11e6-909f-e18ebd736216.png)

**Comment by kevindherman** [comment]
@jlyon this works well on the form but the link displays in full on the agency page. Perhaps that link should be hidden if it's not an email since it's going to a page within the menu structure. 

https://san-rafael-ca.proudcity.com/departments/city-managers-office/
![screenshot 2016-09-20 15 25 32](https://cloud.githubusercontent.com/assets/6032426/18685546/89215be2-7f46-11e6-81fb-7ac2233b2710.png)

**Comment by jlyon** [comment]
@kevindherman Fixed this.  It now says Contact us.

**Comment by kevindherman** [comment]
Perfect.
