### ISSUE TITLE
SR: Voter App Feedback

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#624]
Hey Kevin!

I think the voter widget has a lot of potential, but our City Clerk has a couple questions:
1.      Where is ProudCity getting this information from? Is ProudCity getting the information from another government agency? How can we know that everything in the widget is accurate?
2.      The polling place map widget isn’t populating.
3.      When you click on “vote” when you are already in the “vote box, it blanks out the screen:

![unnamed](https://cloud.githubusercontent.com/assets/6032426/19544717/ba49f7dc-9635-11e6-906a-fabad669d05d.jpg)

**Comment by jlyon** [comment]
As it says in the footer, we are getting the information from the Google Civic Information API (https://developers.google.com/civic-information/).  They get most of their information from the Voter Information project (http://votinginfoproject.org/), which is a new partnership of state election officials, foundations, and leading technology companies in the U.S. working together to increase civic engagement.  We try to be up-front about where the data is coming from.

- [ ] The polling place map widget isn’t populating.
This is probably because of their specific address. Maybe we should start on the issues tab in these instances.

- [ ] When you click on “vote” when you are already in the “vote box, it blanks out the screen
@todo

**Comment by jlyon** [comment]
Moving back to backlog since the election is over.
