### ISSUE TITLE
Change "Other ways to pay" title to "Payment info"

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#641]
Under Make a Payment, Water/Sewer/Storm Utilities: https://www.cityofportorchard.us/#/city/payments/watersewerrefuse
Could we have the line 'Other ways to pay' removed?
Thanks,

![screenshot 2016-10-25 15 57 12](https://cloud.githubusercontent.com/assets/6032426/19702016/e3b1e996-9acb-11e6-9927-a50787478717.png)

**Comment by jlyon** [comment]
Updated this so that if the Content field on a Payment is blank, the "Other Ways to Pay" title won't appear:
![screenshot from 2016-11-02 16 39 58](https://cloud.githubusercontent.com/assets/550909/19951438/3a73141c-a11b-11e6-9dce-4148375c149f.png)

![screenshot from 2016-11-02 16 41 02](https://cloud.githubusercontent.com/assets/550909/19951441/3ea268e4-a11b-11e6-85d9-5ed97a893e68.png)

**Comment by kevindherman** [comment]
@jlyon sometimes that text area is used to for information that isn't necessarily "other ways to pay" like on PO. 

I think we might want to remove that phrase or edit it to Payment Info or something like that.

**Comment by jlyon** [comment]
I think changing the title to Payment Info makes sense.

**Comment by kevindherman** [comment]
@jlyon I cleared my cache and I'm still seeing "other ways to pay" rather than "payment info".

Did that part of this ticket make it into the release?

**Comment by jlyon** [comment]
Looks like maybe it didn't.  Is this urgent, or would next release be ok? @kevindherman

**Comment by kevindherman** [comment]
@jlyon not urgent as long as it doesn't get bumped past the next release.

**Comment by jlyon** [comment]
@kevindherman This has been pushed
