### ISSUE TITLE
Lucas: documents drag and drop question

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#693]
This is the only reported casualty of changing the default ordering for documents. Is there anything we can do to help in the short term before they go live in two weeks or should he just do it manually?

Hello,

The City of Lucas likes the ability to drag and drop document order but we already had them all sorted by date. Is there an easy way for me to sort them back by date and then use the drag and drop going forward? When you sort the "date" column the change/save order functionality goes away.

Thank you!

**Comment by jlyon** [comment]
@kevindherman Unfortunately there's no way to easily work with a hybrid ordering system.  I'll dig into this a little more after the release to see if there's some way for me to automatically set the draggable order to the date.  Re-ordering 800 documents would be a real pain!

He's correct that you can't drag and drop once you have changed the order (because that could really break something).
