### ISSUE TITLE
WC: Search

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#71]
- [x] fix search in modal
- [x] settings
- [x] implement standard site search
- [x] focus on text field w overlay appears

**Comment by kevindherman** [comment]
When I click into the search box on the homepage the white popup comes up but the page is blank. This is happening in an updated version of Chrome.

**Comment by kevindherman** [comment]
@jlyon @aschmoe  Was able to use the search by using the  search icon in the top right. I searched "police" and it brought up mostly baltimorecity.gov stuff. Probably need to clear that all out.

**Comment by aschmoe** [comment]
@kevindherman so are you still having the issue with the search box?  That should have been fixed yesterday

**Comment by kevindherman** [comment]
tested again and the search box is working, just the results are funky now.

On Wed, Feb 3, 2016 at 2:12 PM, Alex Schmoe <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> so are you still having
> the issue with the search box? That should have been fixed yesterday
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/71#issuecomment-179409163>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by aschmoe** [comment]
@kevin added normal search results

**Comment by kevindherman** [comment]
when you click on an "answers" search result it goes to the answers section but not to the actually answer from the search.

**Comment by aschmoe** [comment]
Kevin please refresh and give specifics, in my testing this was working
fine.

**Comment by kevindherman** [comment]
It works fine on the suggested search results. However, if you hit enter to complete submitting the search, clicking on an answers result does not bring  you to that specific answer. 

I have attached two screenshots since the search results look different for suggested results and when you submit a search (hit enter). 

Sorry for not explaining in more detail, let me know if it's still unclear. 

![screenshot search results after enter](https://cloud.githubusercontent.com/assets/6032426/12821682/63c9c1b8-cb32-11e5-8b73-071e17455cd8.png)
![screenshot suggested search](https://cloud.githubusercontent.com/assets/6032426/12821681/63c9480a-cb32-11e5-8ad5-fffd57e214cc.png)

**Comment by jlyon** [comment]
would also be nice to weight autocomplete results
