### ISSUE TITLE
Upgrade WP core to 4.7

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#739]
Issues with the rest api filter[]

Links:
https://developer.wordpress.org/rest-api/adding-rest-api-support-for-custom-content-types/#custom-link-relationships
https://developer.wordpress.org/rest-api/reference/settings/ 
https://developer.wordpress.org/rest-api/adding-rest-api-support-for-custom-content-types/

**Comment by jlyon** [comment]
@aschmoe Upgraded the db, but I'm still seeing the issue with all posts showing from wp-api: https://beta.proudcity.com/#/city/answers/business-tax/

**Comment by aschmoe** [comment]
https://wordpress.org/support/topic/wordpress-4-7-custom-taxonomy-filter-stopped-working/

^^ This turned out to be the magic entry point into understanding what was going on... turns out this extra plugin was necessary https://github.com/WP-API/rest-filter to allow for the filter functionality which did not make it into core.
