### ISSUE TITLE
Auth0 look at session length

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#902]
@kevindherman It seems like these should be lasting 10hrs.

A few questions:
1. Did you login this morning?
2. When it logged out, were you in the middle of doing something? What happened?
3. What site were you on?
4. Do you know if it happened after the release, but before the login page changes (ie on Fri)?

**Comment by kevindherman** [comment]
1- I logged in this morning
2- I had a couple of tabs open so it's hard to tell exactly when the log out occurred. I believe it happened when opening a new page/refreshing. 
3- danvers-ma.proudcity.com
4- after the login page changes Friday.

@jlyon ^

**Comment by jlyon** [comment]
@kevindherman hmm, I logged into SR this morning and I'm still logged in.  I'll keep digging into it this afternoon.

**Comment by kevindherman** [comment]
@jlyon I also noticed since the update was made that even if I login from the url: https://my.proudcity.com/#https://danvers-ma.proudcity.com I get sent to https://example.proudcity.com/#/city/answers instead of Danvers or whatever instance I am trying to login to. I then navigate back to danvers and refresh which add the edit bar to the top of the page.

**Comment by jlyon** [comment]
@kevindherman 

Have there been more reports of this issue?

> err w https://my.proudcity.com/#https://danvers-ma.proudcity.com 
I think I'm gonna skip looking into this and focus on getting the dashboard out the door so this wont be an issue

**Comment by kevindherman** [comment]
@jlyon 
The big difference is that logging in gives me access to all of my sites without needing to go through /#https://city-state.proudcity.com for each one. 

I'll keep an eye on the logging out component.

**Comment by kevindherman** [comment]
I'm still getting logged out after 1-2 hours. However, it is nice that once I'm logged in I have access to all of my sites. Personally, this is probably a wash for how many times I need to log in during a normal day. However, it's probably annoying to a customer with one site and working on it throughout the day.

**Comment by kevindherman** [comment]
@jlyon @aschmoe Danvers: "i can click on the dashboard but can't go beyond that."

**Comment by jlyon** [comment]
@kevindherman I tweaked with these settings today as part of  #932 to hopefully fix this.  Lmk if it worked

**Comment by kevindherman** [comment]
@jlyon @aschmoe I haven't heard about issues from any other city but Kettering said they were being logged out throughout the day and when they would log back in they would be directed to example.proudcity.com, not their Kettering site. 

I'm trying to get more helpful information to replicate the steps.

**Comment by kevindherman** [comment]
1- I just logged in from https://my.proudcity.com/#https://kettering-oh.proudcity.com and used the support@ credentials. 
2- Logged me into kettering dashboard
3- Logged off screen shot:
![screenshot 2017-03-23 16 54 07](https://cloud.githubusercontent.com/assets/6032426/24269922/71b77958-0fe9-11e7-9ade-c4b25dad2d2b.png)
4- Went back to https://my.proudcity.com/#https://kettering-oh.proudcity.com and clicked, last logged in as support@proudcity.com 
![screenshot 2017-03-23 16 55 49](https://cloud.githubusercontent.com/assets/6032426/24269972/b0b85974-0fe9-11e7-94db-8f4d64164e76.png)

5- Clicked back to Kettering which logged me out. 
6- I started the process over from https://my.proudcity.com/#https://kettering-oh.proudcity.com without using the "last logged in as" but rather typing out the email and password and noticed that before being directed to the kettering dashboard, the url path flickered example.proudcity.com/# which I think could have something to do with this. 

Either way, tomorrow is Kettering's last work day before the Monday launch so a quick fix is fine by me so that they can get in there.

**Comment by aschmoe** [comment]
@jlyon today I had no issues until I used my.proudcity.com to log in as kevin has suggested, after that, the info@proudcity.com has been alternating between failing and not failing the heartbeat check (no refreshes just watching it sit there).

`{wp-auth-check: false, server_time: 1490309709}` -> `{wp-auth-check: true, server_time: 1490309829}`

really strange... literally if you let it sit a bit after it informs you "Your session has expired. Please log in to continue where you left off." it will log you back in.

**Comment by aschmoe** [comment]
this seems to only be happening with kettering.

**Comment by aschmoe** [comment]
... and now it seems to be working fine.  I don't know.

**Comment by kevindherman** [comment]
@jlyon @aschmoe the issue that came and went with just Kettering is now happening on San Rafael.

**Comment by kevindherman** [comment]
One of the users at Colma reported issues but I was able to login from my.proudcity.com.

**Comment by kevindherman** [comment]
@jlyon @aschmoe I can't get into SR from my.proudcity.com/#https://www.cityofsanrafael.org

When I go ^ route, it logs me into example.proudcity.com and if I refresh the SR site in another tab I'm still logged out (that approached worked last week). 

Next try I attempted logging in from https://www.cityofsanrafael.org/wp-login which redirected me to https://www.cityofsanrafael.org/wp-login.php?redirect_to=https%3A%2F%2Fwww.cityofsanrafael.org%2Fwp-admin%2F&reauth=1

![screenshot 2017-03-28 11 11 28](https://cloud.githubusercontent.com/assets/6032426/24412755/53f9f1f4-13a7-11e7-8c99-ed028a4b168e.png)

After selecting log in, that same screen just refreshed without logging in. 

I then deleted the path after /wp-login and got a page not found:
https://www.cityofsanrafael.org/wp-login
![screenshot 2017-03-28 11 14 44](https://cloud.githubusercontent.com/assets/6032426/24412925/d4f0d4d0-13a7-11e7-94bd-1afd491649ce.png)
