### ISSUE TITLE
WC: random post

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#904]
Someone from Erika's account posted a spam article:

https://www.westcarrollton.org/cell-phone-tracker-provided-by-phonospy-help/
![screenshot 2017-03-08 15 33 52](https://cloud.githubusercontent.com/assets/6032426/23722941/4601156a-0415-11e7-97b1-67cd70eeb0ad.png)

I have trashed it. Let me know once you have taken a look at it and I will delete permanently.

**Comment by jlyon** [comment]
@kevindherman Yes, I'm seeing the same it was posted exactly at midnight on 2017-03-07 00:00:00, so it seems like it was probably scheduled to be posted.  It's possible that this could have been created earlier and scheduled to be posted at that specific date/time.  Unfortunately I can't really debug too much more than that because our login log only goes back 2 days. 

I created a calendar event to check in on the site every two days for the next couple weeks.

**Comment by kevindherman** [comment]
@jlyon got it.

Just permanently deleted the post.
