### ISSUE TITLE
Kettering: Allow jobs taxonomy to be multi-slect

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#936]
From email:

Tracy, Patti and Lindsey and I went through the process to post on the old site and the new site, as well as how the postings are presenting and we need to see if there are any other options or methods to post positions. 

For instance, is it possible to change the new site's back page to include fillable fields to match the new ones? The "copy/paste" concept is not super efficient given that every time we change the status of a position (closed, reviewing resumes, interviews) the whole posting has to be updated and re-posted to show the status change.  We change the status to communicate to applicants where we are in the process and often refer them to the status line rather than calling.

Also, is there a way to break the postings into categories?  Currently the open positions show first and then the closed ones.  On the new page an applicant has to really dig to determine if a positions is open or closed (they are jumbled) or when the deadline is.  The presentation of the postings on the new site is less user friendly than the old at this point.

Tracy has attached screen shots to show the differences.

Also, is there a way to put and "under construction" note or something until Tracy can manually correct the 31 postings that are on there right now.  I know you are under a really tight deadline, but it would be helpful if we could all chat tomorrow afternoon, so we could find a better solution.  Thanks.

**Comment by kevindherman** [comment]
@aschmoe Stacy asked about two more items on the jobs page that would help with the multi-select. What do you think of these items (she posted to trello):

Thank you again for adjusting widget so that we can select multiple descriptors for each job.

Next:

Is there any way to allow us to change the order in which the categories appear for each job? Right now it appears to be alphabetical. Most important category for us is recruitment status, followed by job type, then department.

Is there any way to change the colors of the descriptors as they appear in the job list? Right now the original job type categories are various colors and all the new ones are grey. This is leading to some confusion. We would either like each category to be different colors ( i.e.- job type - blue, recruitment status - red, department - green) or we would like all of them to be one color like the city maroon.

Thanks.

**Comment by kevindherman** [comment]
@aschmoe just want to make sure the last comment didn't get lost with this being in the last release. let me know what you think.
