### ISSUE TITLE
inconsistent widget alignment on department pages

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#937]
The page title and text aligns differently between primary and secondary pages with departments.

https://colma-ca.proudcity.com/departments/public-works-engineering/

Colma put together this comparison which is helpful to see the difference:
[ProudCity_BugReport_-_Text_alignment.pdf](https://github.com/proudcity/wp-proudcity/files/873750/ProudCity_BugReport_-_Text_alignment.pdf)

**Comment by aschmoe** [comment]
@kevindherman 

the first issue doesn't appear to me happening for me see: https://www.ketteringoh.org/office-of-the-mayor/ (no page-title widget)

The second one seems a little redundant due to the page title being printed in the page-header widget.  I can look into coming up with a solution, but simply removing the title seems appropriate for this particular case.  Thoughts?

**Comment by kevindherman** [comment]
@aschmoe makes sense. I'll talk to them about it on our call today.
