### ISSUE TITLE
/safe page

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#976]
Noticed this certification on carbon.utah.gov: 

https://seal.digicert.com/seals/popup/?tag=6RmVVzj8&url=www.carbon.utah.gov&lang=en&cbr=1492629659804

This is a great way to publicly expose/promote security status.

Maybe from PC side it's a default /safe page that has a similar checklist and somehow ties into dashboard powered by GovReady. Great way to institute a standard and pair with our products.

**Comment by jlyon** [comment]
@aschmoe what do you think?  SSL cert companies are always trying to "get you to add their seal" to their site after you buy a cert. I personally feel like it's because they're after free advertising.

If we want to do something, I think it would make sense to add it to the actions bar and have it link out to something impartial like https://www.ssllabs.com/ssltest/analyze.html?d=ketteringoh.org&latest:

**Comment by lukefretwell** [comment]
@jlyon @aschmoe just noticing this. I ❤️  it!
