### ISSUE TITLE
ProudCity Notifications

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#982]
Let's figure out a way to better address alerts, particularly topic-based/timely messages that users can subscribe to via email.

Something similar to or exactly like: https://wordpress.org/plugins/email-subscribers

**Comment by kevindherman** [comment]
@jlyon @aschmoe this came up in looking at this example: http://novato.org/government/community-development/planning-division/planning-projects

The idea is that if an update is made to one of the projects that subscribers are automatically alerted via email.

**Comment by kevindherman** [comment]
from @jlyon 

https://blog.mailchimp.com/rss-to-email-tutorial/

If you’re a heavy blogger, you’re probably wondering if it’s anything like Feedburner or Feedblitz or the other bajillions of RSS-to-email tools out there. No. Mainly because with MailChimp, you can use your own highly-customized HTML email templates, and we provide open and click tracking, bounce management, list cleaning, spam filter check, and more.

Other links:
http://novato.org/government/community-development/planning-division/planning-projects/oakmont-senior-living

https://www.twilio.com/notify

https://aws.amazon.com/sns/

**Comment by kevindherman** [comment]
Note: Kettering asked about setting up RSS or alerts for their jobs/news.

**Comment by lukefretwell** [comment]
@kevindherman is this issue no longer relevant?
